# Generated by Django 5.2.17 on 2026-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('published', 'published')], default='Draft', max_length=20),
        ),
    ]
